#!/usr/bin/env bash
# self-learn-a43bf00c-about-to-pipe-a.sh — PreToolUse guard, generated by self-learn from lrn-a43bf00c.
# Register manually in ~/.claude/settings.json (matcher: "Bash");
# the symlink into ~/.claude/hooks/ materializes via ./install.sh.
# NEVER hand-edit this file — supersede the record instead (08 §8.1
# rollback pin); a hand edit silently drifts from its record.
# DENY = exit 2 (stderr shown) · ALLOW = exit 0 · malformed input FAILS
# CLOSED (precedent: universal-directory-organizer/organizer-guard.sh).

set -uo pipefail
trap 'echo "self-learn lrn-a43bf00c: guard error on line $LINENO — failing closed" >&2; exit 2' ERR

if ! command -v jq &>/dev/null; then
    echo "self-learn lrn-a43bf00c: jq required but not found — failing closed" >&2
    exit 2
fi

INPUT=$(cat)
# Empty stdin is malformed input, not "no tool" — fail closed. (jq exits 0
# with no output on empty input, which would otherwise fall through to
# the allow arm below.)
if [[ -z "${INPUT//[[:space:]]/}" ]]; then
    echo "self-learn lrn-a43bf00c: empty hook input — failing closed" >&2
    exit 2
fi
TOOL=$(jq -r '.tool_name // empty' <<<"$INPUT")

case "$TOOL" in
    Bash)
        VALUE=$(jq -r '.tool_input.command // empty' <<<"$INPUT")
        ;;
    *)
        # Not a guarded tool — the matcher should prevent this; allow.
        trap - ERR
        exit 0
        ;;
esac

# Named field absent/empty: nothing to match against — allow (precedent).
if [[ -z "$VALUE" ]]; then
    trap - ERR
    exit 0
fi

# Pre-flight the pattern itself: grep -E rc ≥ 2 = broken regex. Inside an
# `if` a grep error would fall through to ALLOW — catch it and fail closed.
PROBE_RC=0
grep -qE -- '(bws[[:space:]]+secret[[:space:]]+list|bw[[:space:]]+list[[:space:]]+items)[^|]*\|[^|]*(awk|sed|grep)' <<<"" || PROBE_RC=$?
if [[ "$PROBE_RC" -ge 2 ]]; then
    echo "self-learn lrn-a43bf00c: guard regex is invalid — failing closed" >&2
    exit 2
fi

MATCH_RC=0
grep -qE -- '(bws[[:space:]]+secret[[:space:]]+list|bw[[:space:]]+list[[:space:]]+items)[^|]*\|[^|]*(awk|sed|grep)' <<<"$VALUE" || MATCH_RC=$?
if [[ "$MATCH_RC" -eq 0 ]]; then
    echo 'self-learn lrn-a43bf00c: an unverified awk/sed/grep filter on secret-listing output can silently print values in full — use jq to select fields structurally, or list names only, instead.' >&2
    exit 2
fi
if [[ "$MATCH_RC" -ge 2 ]]; then
    echo "self-learn lrn-a43bf00c: guard regex failed — failing closed" >&2
    exit 2
fi

trap - ERR
exit 0
